// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ArenaConfigHandle : RemoteTableHandle<EventContext, ArenaConfig>
        {
            protected override string RemoteTableName => "arena_config";

            public sealed class IdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(ArenaConfig row) => row.Id;

                public IdUniqueIndex(ArenaConfigHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal ArenaConfigHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }
        }

        public readonly ArenaConfigHandle ArenaConfig;
    }
}
