// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class CircleHandle : RemoteTableHandle<EventContext, Circle>
        {
            protected override string RemoteTableName => "circle";

            public sealed class CircleIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(Circle row) => row.CircleId;

                public CircleIdUniqueIndex(CircleHandle table) : base(table) { }
            }

            public readonly CircleIdUniqueIndex CircleId;

            internal CircleHandle(DbConnection conn) : base(conn)
            {
                CircleId = new(this);
            }

            protected override object GetPrimaryKey(Circle row) => row.CircleId;
        }

        public readonly CircleHandle Circle;
    }

    public sealed class CircleCols
    {
        public global::SpacetimeDB.Col<Circle, uint> CircleId { get; }
        public global::SpacetimeDB.Col<Circle, StdbVector2> Pos { get; }
        public global::SpacetimeDB.Col<Circle, StdbVector2> Velocity { get; }
        public global::SpacetimeDB.Col<Circle, float> Radius { get; }

        public CircleCols(string tableName)
        {
            CircleId = new global::SpacetimeDB.Col<Circle, uint>(tableName, "circle_id");
            Pos = new global::SpacetimeDB.Col<Circle, StdbVector2>(tableName, "pos");
            Velocity = new global::SpacetimeDB.Col<Circle, StdbVector2>(tableName, "velocity");
            Radius = new global::SpacetimeDB.Col<Circle, float>(tableName, "radius");
        }
    }

    public sealed class CircleIxCols
    {
        public global::SpacetimeDB.IxCol<Circle, uint> CircleId { get; }

        public CircleIxCols(string tableName)
        {
            CircleId = new global::SpacetimeDB.IxCol<Circle, uint>(tableName, "circle_id");
        }
    }
}
