// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class CircleHandle : RemoteTableHandle<EventContext, Circle>
        {
            protected override string RemoteTableName => "circle";

            public sealed class CircleIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(Circle row) => row.CircleId;

                public CircleIdUniqueIndex(CircleHandle table) : base(table) { }
            }

            public readonly CircleIdUniqueIndex CircleId;

            internal CircleHandle(DbConnection conn) : base(conn)
            {
                CircleId = new(this);
            }

            protected override object GetPrimaryKey(Circle row) => row.CircleId;
        }

        public readonly CircleHandle Circle;
    }
}
