// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AddCircleHandler(ReducerEventContext ctx, SpacetimeDB.Types.StdbVector2 pos, float radius);
        public event AddCircleHandler? OnAddCircle;

        public void AddCircle(SpacetimeDB.Types.StdbVector2 pos, float radius)
        {
            conn.InternalCallReducer(new Reducer.AddCircle(pos, radius));
        }

        public bool InvokeAddCircle(ReducerEventContext ctx, Reducer.AddCircle args)
        {
            if (OnAddCircle == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAddCircle(
                ctx,
                args.Pos,
                args.Radius
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AddCircle : Reducer, IReducerArgs
        {
            [DataMember(Name = "pos")]
            public StdbVector2 Pos;
            [DataMember(Name = "radius")]
            public float Radius;

            public AddCircle(
                StdbVector2 Pos,
                float Radius
            )
            {
                this.Pos = Pos;
                this.Radius = Radius;
            }

            public AddCircle()
            {
                this.Pos = new();
            }

            string IReducerArgs.ReducerName => "add_circle";
        }
    }
}
