// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AddCirclesHandler(ReducerEventContext ctx, uint count);
        public event AddCirclesHandler? OnAddCircles;

        public void AddCircles(uint count)
        {
            conn.InternalCallReducer(new Reducer.AddCircles(count));
        }

        public bool InvokeAddCircles(ReducerEventContext ctx, Reducer.AddCircles args)
        {
            if (OnAddCircles == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAddCircles(
                ctx,
                args.Count
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AddCircles : Reducer, IReducerArgs
        {
            [DataMember(Name = "count")]
            public uint Count;

            public AddCircles(uint Count)
            {
                this.Count = Count;
            }

            public AddCircles()
            {
            }

            string IReducerArgs.ReducerName => "add_circles";
        }
    }
}
