// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AddCirclesHandler(ReducerEventContext ctx, uint count);
        public event AddCirclesHandler? OnAddCircles;

        public void AddCircles(uint count)
        {
            conn.InternalCallReducer(new Reducer.AddCircles(count), this.SetCallReducerFlags.AddCirclesFlags);
        }

        public bool InvokeAddCircles(ReducerEventContext ctx, Reducer.AddCircles args)
        {
            if (OnAddCircles == null) return false;
            OnAddCircles(
                ctx,
                args.Count
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AddCircles : Reducer, IReducerArgs
        {
            [DataMember(Name = "count")]
            public uint Count;

            public AddCircles(uint Count)
            {
                this.Count = Count;
            }

            public AddCircles()
            {
            }

            string IReducerArgs.ReducerName => "add_circles";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags AddCirclesFlags;
        public void AddCircles(CallReducerFlags flags) => AddCirclesFlags = flags;
    }
}
