// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SimulatePhysicsHandler(ReducerEventContext ctx, PhysicsTimer timer);
        public event SimulatePhysicsHandler? OnSimulatePhysics;

        public void SimulatePhysics(PhysicsTimer timer)
        {
            conn.InternalCallReducer(new Reducer.SimulatePhysics(timer), this.SetCallReducerFlags.SimulatePhysicsFlags);
        }

        public bool InvokeSimulatePhysics(ReducerEventContext ctx, Reducer.SimulatePhysics args)
        {
            if (OnSimulatePhysics == null) return false;
            OnSimulatePhysics(
                ctx,
                args.Timer
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SimulatePhysics : Reducer, IReducerArgs
        {
            [DataMember(Name = "_timer")]
            public PhysicsTimer Timer;

            public SimulatePhysics(PhysicsTimer Timer)
            {
                this.Timer = Timer;
            }

            public SimulatePhysics()
            {
                this.Timer = new();
            }

            string IReducerArgs.ReducerName => "simulate_physics";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags SimulatePhysicsFlags;
        public void SimulatePhysics(CallReducerFlags flags) => SimulatePhysicsFlags = flags;
    }
}
