// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
import { Circle } from "./circle_type";
import { StdbVector2 as __StdbVector2 } from "./stdb_vector_2_type";

import { EventContext, Reducer, RemoteReducers, RemoteTables } from ".";

/**
 * Table handle for the table `circle`.
 *
 * Obtain a handle from the [`circle`] property on [`RemoteTables`],
 * like `ctx.db.circle`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.circle.on_insert(...)`.
 */
export class CircleTableHandle {
  tableCache: TableCache<Circle>;

  constructor(tableCache: TableCache<Circle>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<Circle> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `circle_id` unique index on the table `circle`,
   * which allows point queries on the field of the same name
   * via the [`CircleCircleIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.circle.circle_id().find(...)`.
   *
   * Get a handle on the `circle_id` unique index on the table `circle`.
   */
  circle_id = {
    // Find the subscribed row whose `circle_id` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: number): Circle | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.circle_id, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: Circle) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: Circle) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: Circle) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: Circle) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: Circle, newRow: Circle) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: Circle, newRow: Circle) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
