// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
import { StdbVector2 as __StdbVector2 } from "./stdb_vector_2_type";

export type Circle = {
  circleId: number,
  pos: __StdbVector2,
  velocity: __StdbVector2,
  radius: number,
};

/**
 * A namespace for generated helper functions.
 */
export namespace Circle {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("circleId", AlgebraicType.createU32Type()),
      new ProductTypeElement("pos", __StdbVector2.getTypeScriptAlgebraicType()),
      new ProductTypeElement("velocity", __StdbVector2.getTypeScriptAlgebraicType()),
      new ProductTypeElement("radius", AlgebraicType.createF32Type()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: Circle): void {
    Circle.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): Circle {
    return Circle.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


