// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ArenaConfig
    {
        [DataMember(Name = "id")]
        public uint Id;
        [DataMember(Name = "width")]
        public float Width;
        [DataMember(Name = "height")]
        public float Height;

        public ArenaConfig(
            uint Id,
            float Width,
            float Height
        )
        {
            this.Id = Id;
            this.Width = Width;
            this.Height = Height;
        }

        public ArenaConfig()
        {
        }
    }
}
