// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Circle
    {
        [DataMember(Name = "circle_id")]
        public uint CircleId;
        [DataMember(Name = "pos")]
        public StdbVector2 Pos;
        [DataMember(Name = "velocity")]
        public StdbVector2 Velocity;
        [DataMember(Name = "radius")]
        public float Radius;

        public Circle(
            uint CircleId,
            StdbVector2 Pos,
            StdbVector2 Velocity,
            float Radius
        )
        {
            this.CircleId = CircleId;
            this.Pos = Pos;
            this.Velocity = Velocity;
            this.Radius = Radius;
        }

        public Circle()
        {
            this.Pos = new();
            this.Velocity = new();
        }
    }
}
